const constants ={
    ADD_CATEGORY: "ADD_CATEGORY",
    ADD_CATEGORIES: "ADD_CATEGORIES",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    ADD_ISSUE: "ADD_ISSUE",
    FETCH_ISSUES: "FETCH_ISSUES",
    ADD_ISSUES: "ADD_ISSUES",
}
export default constants;